apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Chart.Name }}-deploy
  labels:
    app: {{ .Chart.Name }}-{{ .Values.app.version }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:
      containers:
        - name: app
          image: {{ .Values.docker.image }}
          imagePullPolicy: {{ .Values.docker.pullPolicy | default "Always" | quote }}
          # envFrom:
          #   secretRef:
          #     name: postgres-postgresql

          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB_NAME
            value: "postgres"
          - name: POSTGRES_HOST
            value: "postgres"
