app:
  version: 0.0.1
docker:
  image: shortly # Must match skaffold.yaml Artifact name
  pullPolicy: Never # Always use local image
postgres:
  mount_path: "/Users/ban/Desktop/playground/shortly/postgres"

auth:
  username: postgres
  password: postgres
  database: postgres
